# Generated by Django 3.2.3 on 2025-05-30 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_auto_20250529_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(help_text='Выберите рецепты для покупки ингридиентов', related_name='in_shopping_lists', to='recipes.Recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglist',
            unique_together={('user',)},
        ),
    ]
