# Generated by Django 3.2.3 on 2025-05-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20250530_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='unit',
            field=models.PositiveIntegerField(default=1, help_text='Введите Количество ингредиента', verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
    ]
