# Generated by Django 3.2.3 on 2025-05-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_rename_unit_ingredients_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='amount',
        ),
    ]
