# Generated by Django 3.2.3 on 2025-06-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_rename_recipes_shoppinglist_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='descriptions',
            new_name='text',
        ),
    ]
