# Generated by Django 3.2.3 on 2025-06-06 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_recipe_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
