# Generated by Django 3.2.3 on 2025-05-30 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_remove_ingredients_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Укажите количество', max_digits=6, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Укажите Ингредиенты', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients', verbose_name='Ингредиенты')),
                ('shopping_list', models.ForeignKey(help_text='Укажите список покупок', on_delete=django.db.models.deletion.CASCADE, to='recipes.shoppinglist', verbose_name='Список покупок')),
            ],
            options={
                'verbose_name': 'Ингридиент в списке покупок',
                'verbose_name_plural': 'Ингридиенты в списках покупок',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Укажите количество', max_digits=6, verbose_name='Количество')),
                ('ingredient', models.ForeignKey(help_text='Укажите ингредиент', on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients', verbose_name='Ингредиент')),
                ('recipe', models.ForeignKey(help_text='Укажите рецепт', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Ингридиент в рецепте',
                'verbose_name_plural': 'Ингридиенты в рецепте',
            },
        ),
    ]
